jdbc:
  ds:
    url: jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.balance.*.model
  mapper-locations: classpath:mapper/*.xml

#mybatis配置